-- MySQL Script generated by MySQL Workbench
-- Fri Oct  7 17:58:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_alumnos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_alumnos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_alumnos` DEFAULT CHARACTER SET utf8 ;
USE `db_alumnos` ;

-- -----------------------------------------------------
-- Table `db_alumnos`.`tbl_carreras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_alumnos`.`tbl_carreras` (
  `codigo_carrera` INT NOT NULL AUTO_INCREMENT,
  `nombre_carrera` VARCHAR(100) NULL,
  `cantidad_asignaturas` INT NULL,
  PRIMARY KEY (`codigo_carrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_alumnos`.`tbl_centros_estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_alumnos`.`tbl_centros_estudio` (
  `codigo_centro` INT NOT NULL AUTO_INCREMENT,
  `nombre_centro_estudio` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo_centro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_alumnos`.`tbl_alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_alumnos`.`tbl_alumnos` (
  `codigo_alumno` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `edad` INT NOT NULL,
  `genero` VARCHAR(1) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `codigo_carrera` INT NOT NULL,
  `codigo_centro` INT NOT NULL,
  PRIMARY KEY (`codigo_alumno`),
  INDEX `fk_tbl_alumnos_tbl_centros_estudio1_idx` (`codigo_centro` ASC),
  INDEX `fk_tbl_alumnos_tbl_carreras_idx` (`codigo_carrera` ASC),
  CONSTRAINT `fk_tbl_alumnos_tbl_carreras`
    FOREIGN KEY (`codigo_carrera`)
    REFERENCES `db_alumnos`.`tbl_carreras` (`codigo_carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_alumnos_tbl_centros_estudio1`
    FOREIGN KEY (`codigo_centro`)
    REFERENCES `db_alumnos`.`tbl_centros_estudio` (`codigo_centro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
